name: Package kedro project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup
    - name: Run ruff linter
      run: pipenv run ruff check $(git ls-files '*.py') --show-files

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Run tests
      run: pipenv run pytest

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Package project
        run: |
          pipenv requirements --exclude-markers | tail -n +2 > requirements.txt
          pipenv run kedro package
      - name: Run package
        run: |
          bash scripts/authenticate.sh ${{ vars.aws_access_key_id }} ${{ secrets.aws_secret_access_key }}
          pip install dist/raccoon_spotter*
          python -m raccoon_spotter